export default {
  kind: "youtube#videoListResponse",
  etag: "djm9EGulgyga0bmCjbhyRfX57Sw",
  items: [
    {
      kind: "youtube#video",
      etag: "EPU3Jhv8wucJAPEIU5yt0mdX2s4",
      id: "Fij7x3h_S6Y",
      snippet: {
        publishedAt: "2023-07-27T00:05:04Z",
        channelId: "UCJbYdyufHR-cxOuY96KIoqA",
        title: "AMP FRESHMAN CYPHER 2023",
        description:
          "CHECK OUT APPAREL DROP 2 ⚡ HTTPS://AMP.SHOP\n\nWE RECORDED A PODCAST!! SUB NOW https://www.youtube.com/channel/UC51ypdbMnEyRb9f9MCOg_Vg?sub_confirmation=1\n\nVIDEO DIRECTED & EDITED BY JESSE LOMAX & FOURTH FRAME STUDIOS\n\nAMP AMP AMP AMP\n📸 Follow us on Instagram: https://www.instagram.com/ampexclusive\n🦅 Follow us on Twitter: https://twitter.com/ampexclusive\n\n⚡️⚡️AMP⚡️⚡️\n\n⚡️Fanum aka JustFanum\n🎥 https://www.youtube.com/c/FanumReacts/videos\n📸 https://www.instagram.com/elfanum/\n🦅 https://twitter.com/FanumTV\n\n⚡️Duke aka Duke Dennis\n🎥 https://www.youtube.com/c/DeeBlockDukeDennis\n📸 https://www.instagram.com/duke_dennis/\n🦅 https://twitter.com/ImDukeDennis\n\n⚡️Agent aka Agent 00\n🎥 https://www.youtube.com/user/CallMeAgent00\n📸 https://www.instagram.com/callmeagentzero/\n🦅 https://twitter.com/CallMeAgent00\n\n⚡️Davis aka ImDavisss\n🎥  https://www.youtube.com/c/ItsDavisss\n📸 https://www.instagram.com/imdavisssyt/\n🦅 https://twitter.com/imdavisss\n\n⚡️ Kai aka Kai Cenat\n🎥 https://www.youtube.com/c/KaiCenat\n📸 https://www.instagram.com/kai_cenattv/\n🦅 https://twitter.com/KaiCenat\n\n⚡️Chris aka chrisnxtdoor\n🎥 https://www.youtube.com/watch?v=yEREEVk06ZM\n📸 https://www.instagram.com/chrisnxtdoor_/\n🦅 https://twitter.com/chrisnxtdoor_",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "AMP",
        tags: [
          "AMP FRESHMAN CYPHER 2023",
          "AMP CYPHER",
          "AMP FRESHMAN CYPHER",
          "KAI CENAT",
          "DUKE DENNIS",
          "FANUM",
          "AGENT 00",
          "CHRISNXTDOOR",
          "IMDAVISSS",
          "LIL YACHTY",
          "KAYSAN",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "AMP FRESHMAN CYPHER 2023",
          description:
            "CHECK OUT APPAREL DROP 2 ⚡ HTTPS://AMP.SHOP\n\nWE RECORDED A PODCAST!! SUB NOW https://www.youtube.com/channel/UC51ypdbMnEyRb9f9MCOg_Vg?sub_confirmation=1\n\nVIDEO DIRECTED & EDITED BY JESSE LOMAX & FOURTH FRAME STUDIOS\n\nAMP AMP AMP AMP\n📸 Follow us on Instagram: https://www.instagram.com/ampexclusive\n🦅 Follow us on Twitter: https://twitter.com/ampexclusive\n\n⚡️⚡️AMP⚡️⚡️\n\n⚡️Fanum aka JustFanum\n🎥 https://www.youtube.com/c/FanumReacts/videos\n📸 https://www.instagram.com/elfanum/\n🦅 https://twitter.com/FanumTV\n\n⚡️Duke aka Duke Dennis\n🎥 https://www.youtube.com/c/DeeBlockDukeDennis\n📸 https://www.instagram.com/duke_dennis/\n🦅 https://twitter.com/ImDukeDennis\n\n⚡️Agent aka Agent 00\n🎥 https://www.youtube.com/user/CallMeAgent00\n📸 https://www.instagram.com/callmeagentzero/\n🦅 https://twitter.com/CallMeAgent00\n\n⚡️Davis aka ImDavisss\n🎥  https://www.youtube.com/c/ItsDavisss\n📸 https://www.instagram.com/imdavisssyt/\n🦅 https://twitter.com/imdavisss\n\n⚡️ Kai aka Kai Cenat\n🎥 https://www.youtube.com/c/KaiCenat\n📸 https://www.instagram.com/kai_cenattv/\n🦅 https://twitter.com/KaiCenat\n\n⚡️Chris aka chrisnxtdoor\n🎥 https://www.youtube.com/watch?v=yEREEVk06ZM\n📸 https://www.instagram.com/chrisnxtdoor_/\n🦅 https://twitter.com/chrisnxtdoor_",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT14M",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1578253",
        likeCount: "184132",
        favoriteCount: "0",
        commentCount: "24102",
      },
    },
    {
      kind: "youtube#video",
      etag: "b_C67pvIm3FjyRZJPJDg_7MKOYE",
      id: "UqmUxkRPBS0",
      snippet: {
        publishedAt: "2023-07-26T13:00:07Z",
        channelId: "UCCdbL-yl7Qa_vurbYWdn5SA",
        title: "Ice Spice - Deli",
        description:
          "Music video by Ice Spice performing Deli. 10K Projects/Capitol Records; © 2023 Dolo Entertainment, Inc., under exclusive license to UMG Recordings, Inc. & 10K Projects, LLC.\n\nhttp://vevo.ly/w4uE45",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/UqmUxkRPBS0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/UqmUxkRPBS0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/UqmUxkRPBS0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/UqmUxkRPBS0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/UqmUxkRPBS0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "IceSpiceVEVO",
        tags: [
          "Ice",
          "Spice",
          "Deli",
          "10K",
          "Projects/Capitol",
          "Records",
          "Hip",
          "Hop",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Ice Spice - Deli",
          description:
            "Music video by Ice Spice performing Deli. 10K Projects/Capitol Records; © 2023 Dolo Entertainment, Inc., under exclusive license to UMG Recordings, Inc. & 10K Projects, LLC.\n\nhttp://vevo.ly/w4uE45",
        },
      },
      contentDetails: {
        duration: "PT2M8S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        regionRestriction: {
          blocked: ["BY", "IO", "KP", "RU", "SS"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2002942",
        likeCount: "180706",
        favoriteCount: "0",
        commentCount: "12174",
      },
    },
    {
      kind: "youtube#video",
      etag: "Ymr3JraW5gRU5baKDAhEnWOFl_8",
      id: "qHpLCsZ2fTs",
      snippet: {
        publishedAt: "2023-07-26T03:58:32Z",
        channelId: "UC7_YxT-KID8kRbqZo7MyscQ",
        title: "Five Nights at Freddy's Security Breach: RUIN - Part 1",
        description:
          "The first official free roam Five Nights at Freddy's game got it's first DLC! Step back into the Pizzaplex and explore the Ruin we left behind.\nLISTEN TO DISTRACTIBLE ►► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\n\nPlay FNAF Security Breach RUIN ► https://store.steampowered.com/app/1924720/Five_Nights_at_Freddys_Security_Breach__Ruin/\n\nScary Games Playlist ► https://www.youtube.com/playlist?list=PL3tRBEVW0hiBSFOFhTC5wt75P2BES0rAo\n\nHorror Outro ► https://soundcloud.com/shurkofficial/haunted",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/qHpLCsZ2fTs/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/qHpLCsZ2fTs/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/qHpLCsZ2fTs/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/qHpLCsZ2fTs/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/qHpLCsZ2fTs/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Markiplier",
        tags: [
          "five nights at freddys security breach",
          "fnaf",
          "markiplier",
          "markiplier security breach",
          "markiplier five nights at freddy's",
          "five nights at freddy's",
          "part 1",
          "gaming",
          "gameplay",
          "playthrough",
          "reactions",
          "screaming",
          "jump scares",
          "freddy",
          "chica",
          "bonnie",
          "golden freddy",
          "ruin",
          "ruin dlc",
          "security breach ruin",
        ],
        categoryId: "20",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Five Nights at Freddy's Security Breach: RUIN - Part 1",
          description:
            "The first official free roam Five Nights at Freddy's game got it's first DLC! Step back into the Pizzaplex and explore the Ruin we left behind.\nLISTEN TO DISTRACTIBLE ►► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\n\nPlay FNAF Security Breach RUIN ► https://store.steampowered.com/app/1924720/Five_Nights_at_Freddys_Security_Breach__Ruin/\n\nScary Games Playlist ► https://www.youtube.com/playlist?list=PL3tRBEVW0hiBSFOFhTC5wt75P2BES0rAo\n\nHorror Outro ► https://soundcloud.com/shurkofficial/haunted",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT51M13S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4512247",
        likeCount: "320848",
        favoriteCount: "0",
        commentCount: "18224",
      },
    },
    {
      kind: "youtube#video",
      etag: "DNoHkAKkzxM1rn8WmhxmR9xwlYc",
      id: "xnG4Mfak-Oc",
      snippet: {
        publishedAt: "2023-07-26T20:17:26Z",
        channelId: "UC8p1vwvWtl6T73JiExfWs1g",
        title:
          'UFO whistleblower says U.S. recovered nonhuman "biologics" from crash sites',
        description:
          'Former military intelligence officer-turned-whistleblower David Grusch told House lawmakers Wednesday that he had interviewed government officials who had direct knowledge of aircraft with "nonhuman" origins, and that so-called "biologics" were recovered from some craft. Grusch, who served for 14 years as an intelligence officer in the Air Force and National Geospatial Intelligence Agency, appeared before the House Oversight Committee\'s national security subcommittee alongside two former fighter pilots who had firsthand experience with unidentified aerial phenomena.\n\n#news #ufo #congress \n\nCBS News Streaming Network is the premier 24/7 anchored streaming news service from CBS News and Stations, available free to everyone with access to the Internet. The CBS News Streaming Network is your destination for breaking news, live events and original reporting locally, nationally and around the globe. Launched in November 2014 as CBSN, the CBS News Streaming Network is available live in 91 countries and on 30 digital platforms and apps, as well as on CBSNews.com and Paramount+.\n\nSubscribe to the CBS News YouTube channel: https://youtube.com/cbsnews\nWatch CBS News: https://cbsn.ws/1PlLpZ7c\nDownload the CBS News app: https://cbsn.ws/1Xb1WC8\nFollow CBS News on Instagram: https://www.instagram.com/cbsnews/\nLike CBS News on Facebook: https://facebook.com/cbsnews\nFollow CBS News on Twitter: https://twitter.com/cbsnews\nSubscribe to our newsletters: https://cbsn.ws/1RqHw7T\nTry Paramount+ free: https://bit.ly/2OiW1kZ\n\nFor video licensing inquiries, contact: licensing@veritone.com',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/xnG4Mfak-Oc/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/xnG4Mfak-Oc/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/xnG4Mfak-Oc/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/xnG4Mfak-Oc/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/xnG4Mfak-Oc/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "CBS News",
        tags: [
          "UFO",
          "unidentified flying object",
          "Politics",
          "House Oversight Committee",
          "United States Department of Defense",
          "United States Congress",
          "United States House of Representatives",
        ],
        categoryId: "25",
        liveBroadcastContent: "none",
        localized: {
          title:
            'UFO whistleblower says U.S. recovered nonhuman "biologics" from crash sites',
          description:
            'Former military intelligence officer-turned-whistleblower David Grusch told House lawmakers Wednesday that he had interviewed government officials who had direct knowledge of aircraft with "nonhuman" origins, and that so-called "biologics" were recovered from some craft. Grusch, who served for 14 years as an intelligence officer in the Air Force and National Geospatial Intelligence Agency, appeared before the House Oversight Committee\'s national security subcommittee alongside two former fighter pilots who had firsthand experience with unidentified aerial phenomena.\n\n#news #ufo #congress \n\nCBS News Streaming Network is the premier 24/7 anchored streaming news service from CBS News and Stations, available free to everyone with access to the Internet. The CBS News Streaming Network is your destination for breaking news, live events and original reporting locally, nationally and around the globe. Launched in November 2014 as CBSN, the CBS News Streaming Network is available live in 91 countries and on 30 digital platforms and apps, as well as on CBSNews.com and Paramount+.\n\nSubscribe to the CBS News YouTube channel: https://youtube.com/cbsnews\nWatch CBS News: https://cbsn.ws/1PlLpZ7c\nDownload the CBS News app: https://cbsn.ws/1Xb1WC8\nFollow CBS News on Instagram: https://www.instagram.com/cbsnews/\nLike CBS News on Facebook: https://facebook.com/cbsnews\nFollow CBS News on Twitter: https://twitter.com/cbsnews\nSubscribe to our newsletters: https://cbsn.ws/1RqHw7T\nTry Paramount+ free: https://bit.ly/2OiW1kZ\n\nFor video licensing inquiries, contact: licensing@veritone.com',
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT5M14S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "744703",
        likeCount: "13011",
        favoriteCount: "0",
        commentCount: "6373",
      },
    },
    {
      kind: "youtube#video",
      etag: "ybHiLutsJLpFCY9XVPZ3z_XQvYs",
      id: "eQ35V-wxHqY",
      snippet: {
        publishedAt: "2023-07-26T17:00:11Z",
        channelId: "UCXqV4yoyC_mmZye6VbKFPeQ",
        title: "Poppy Playtime: Chapter 3 - Teaser Trailer #2",
        description:
          "Grab the Exclusive Chapter 3 Merch!\nhttps://poppyplaytime.com/products/poppy-playtime-hour-of-joy-chapter-3-exclusive-tee\n\nYou must stay alive in this unique, horror-puzzle adventure. Try to survive the vengeful toys waiting for you in the abandoned toy factory. Use your GrabPack to hack electrical circuits or nab anything from afar. Explore the mysterious facility... and don't get caught.\n\nFollow the game: \nhttps://linktr.ee/PoppyPlaytimeCo",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/eQ35V-wxHqY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/eQ35V-wxHqY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/eQ35V-wxHqY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/eQ35V-wxHqY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/eQ35V-wxHqY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Mob Entertainment",
        categoryId: "20",
        liveBroadcastContent: "none",
        localized: {
          title: "Poppy Playtime: Chapter 3 - Teaser Trailer #2",
          description:
            "Grab the Exclusive Chapter 3 Merch!\nhttps://poppyplaytime.com/products/poppy-playtime-hour-of-joy-chapter-3-exclusive-tee\n\nYou must stay alive in this unique, horror-puzzle adventure. Try to survive the vengeful toys waiting for you in the abandoned toy factory. Use your GrabPack to hack electrical circuits or nab anything from afar. Explore the mysterious facility... and don't get caught.\n\nFollow the game: \nhttps://linktr.ee/PoppyPlaytimeCo",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT1M50S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1514817",
        likeCount: "114761",
        favoriteCount: "0",
        commentCount: "15239",
      },
    },
    {
      kind: "youtube#video",
      etag: "ATUCh0sTxRln_Gb68V5X--QfBpA",
      id: "II-L8Hq0_i4",
      snippet: {
        publishedAt: "2023-07-27T12:00:08Z",
        channelId: "UCAJFKfQOt3SsccXg5QOcZKQ",
        title: "Tyler Childers - In Your Love (Official Video)",
        description:
          "“In Your Love” is out now: https://tchilders.lnk.to/inyourlove\nPre-Order Rustin’ in the Rain now: https://tchilders.lnk.to/rustinintherain\n\nFollow Tyler on Socials:\nOfficial site: https://tylerchildersmusic.com/collections/all\nFacebook: https://facebook.com/tylerchildersmusic/\nInstagram: https://www.instagram.com/timmytychilders/\nTwitter: https://twitter.com/TTChilders\nTikTok: https://www.tiktok.com/@timmytychildersmusic\n\nLyrics:\n\nI will wait for you\nTil the sun turns into ashes\nAnd bows down to the moon\nI will wait for you\n\nIt’s a long hard war\nAh but I can grin and bare it\nCause I know what the hell I’m fighting for\nAnd I will wait for you\n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nI will stand my ground\nI’m a bad man looking for takers \nYou’re the finest thing around\nSo I will stand my ground  \n\nCause it’s cold out there\nAnd you know some men search for ages\nFor the love that I have found \nSo I will stand my ground \n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nHoney I will wait for you\nHoney I will stand my ground\n\nI will work for you\nTil my hands are tired and bleedin’\nI know what it is from us I’m needin’\nI will work for you\n\nLike a team of mules\nPulling Hell off from its hinges\nIt’s the love that I’ll keep tendin’ \nI will work for you\n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nHoney I will wait for you\nHoney I will stand my ground\nI will work for you \nI will stand my ground\n\nPRODUCTION \nDIRECTOR – Bryan Schlam\nWRITTEN BY – Silas House \nPRODUCED BY– Kacie Barton\nPRODUCED BY– Whitney Wolanin\nPRODUCED BY – Nicholas Robespierre\nPRODUCED BY– Ian Thornton \nPRODUCED BY – Silas House\nSTORY BY – Silas House and Jason Kyle Howard\nPARTNER – Mark De Pace \nPARTNER – Zachary Mortensen\nEXEC PRODUCER – Kacie Barton\nMANAGING DIRECTOR – Alexis Kaplan \nHEAD OF BUSINESS DEV – Justin Medley \nSTAFF COORDINATOR – Andrea Tangelo \nLINE PRODUCER – Whitney Wolanin\nPRODUCTION SUPERVISOR – Loren Greene \nDIRECTOR OF PHOTOGRAPHY – Doug Porter \nPRODUCTION DESIGNER – Amanda Alberto \nWARDROBE STYLIST– Samantha Roe \nHMU – Nichole Lim \nCASTING – Harriet Greenspan  \n1st AD – Eric Williams \n2nd AD – Quinn Cooke \n \nPOST PRODUCTION  - Ghost Robot\nPOST PRODUCTION – Kacie Barton \nEDITOR – Bryan Schlam\nVFX – John Stanch\nCOLOR – Company 3 – Matt Osbourne \nCOLOR PRODUCER – Dan Butler / Matt Moran \n \nTALENT \nJASPER – Colton Haynes \nMATTHEW – James Scully \nNED – Matthew James Ballinger \nELDER JASPER – James Carey \nMINERS \n-Thomas De Braun \n-Brent Greene \n-Russell Terry \n-Benjamin Wilson \nFARMER – Silas House \nFRIENDS \n-Adam Tanaka \n-Andi Tillman \n-Dara Tiller \n-Casey Campbell\nDOCTOR – Robert Ridhage\nBARTENDER – Ashley Barber \nBAR PATRONS \n-Cameron Bortz\n-Hunter Jones \n-William Arthur\n-Steven Handeland\n-Courtne Moran \n-Kayla Powell\n-Jason Howard\n-Reece Hassell\n \nLABEL – RCA RECORDS\nVP, Video & Visual Content Production - Nicholas Robespierre \nDirector, Video & Visual Content Production - Win Smith \nMarketing – Aaron Stern\nMANAGEMENT \nManager – Ian Thornton\nManager – Michael Corcoran \n\n#TylerChilders #InYourLove #RustinInTheRain",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/II-L8Hq0_i4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/II-L8Hq0_i4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/II-L8Hq0_i4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/II-L8Hq0_i4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/II-L8Hq0_i4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "TylerChildersVEVO",
        tags: [
          "tyler childers",
          "can take my hounds to heaven",
          "angel band",
          "tyler childers whitehouse road",
          "tyler childers live",
          "tyler childers jersey giant",
          "tyler childers angel band",
          "tyler childers silas interview",
          "silas interview",
          "tyler childers interview",
          "tyler childers shake the frost",
          "tyler childers all yourn",
          "tyler childers feathered indian",
          "tyler childers all yourn live",
          "tyler childers all yours",
          "silas house",
          "in your love",
          "in your love tyler childers",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Tyler Childers - In Your Love (Official Video)",
          description:
            "“In Your Love” is out now: https://tchilders.lnk.to/inyourlove\nPre-Order Rustin’ in the Rain now: https://tchilders.lnk.to/rustinintherain\n\nFollow Tyler on Socials:\nOfficial site: https://tylerchildersmusic.com/collections/all\nFacebook: https://facebook.com/tylerchildersmusic/\nInstagram: https://www.instagram.com/timmytychilders/\nTwitter: https://twitter.com/TTChilders\nTikTok: https://www.tiktok.com/@timmytychildersmusic\n\nLyrics:\n\nI will wait for you\nTil the sun turns into ashes\nAnd bows down to the moon\nI will wait for you\n\nIt’s a long hard war\nAh but I can grin and bare it\nCause I know what the hell I’m fighting for\nAnd I will wait for you\n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nI will stand my ground\nI’m a bad man looking for takers \nYou’re the finest thing around\nSo I will stand my ground  \n\nCause it’s cold out there\nAnd you know some men search for ages\nFor the love that I have found \nSo I will stand my ground \n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nHoney I will wait for you\nHoney I will stand my ground\n\nI will work for you\nTil my hands are tired and bleedin’\nI know what it is from us I’m needin’\nI will work for you\n\nLike a team of mules\nPulling Hell off from its hinges\nIt’s the love that I’ll keep tendin’ \nI will work for you\n\nWe were never made to run forever\nWe were just meant to go long enough\nTo find what we were chasing after\nI believe I found it here in your love \n\nHoney I will wait for you\nHoney I will stand my ground\nI will work for you \nI will stand my ground\n\nPRODUCTION \nDIRECTOR – Bryan Schlam\nWRITTEN BY – Silas House \nPRODUCED BY– Kacie Barton\nPRODUCED BY– Whitney Wolanin\nPRODUCED BY – Nicholas Robespierre\nPRODUCED BY– Ian Thornton \nPRODUCED BY – Silas House\nSTORY BY – Silas House and Jason Kyle Howard\nPARTNER – Mark De Pace \nPARTNER – Zachary Mortensen\nEXEC PRODUCER – Kacie Barton\nMANAGING DIRECTOR – Alexis Kaplan \nHEAD OF BUSINESS DEV – Justin Medley \nSTAFF COORDINATOR – Andrea Tangelo \nLINE PRODUCER – Whitney Wolanin\nPRODUCTION SUPERVISOR – Loren Greene \nDIRECTOR OF PHOTOGRAPHY – Doug Porter \nPRODUCTION DESIGNER – Amanda Alberto \nWARDROBE STYLIST– Samantha Roe \nHMU – Nichole Lim \nCASTING – Harriet Greenspan  \n1st AD – Eric Williams \n2nd AD – Quinn Cooke \n \nPOST PRODUCTION  - Ghost Robot\nPOST PRODUCTION – Kacie Barton \nEDITOR – Bryan Schlam\nVFX – John Stanch\nCOLOR – Company 3 – Matt Osbourne \nCOLOR PRODUCER – Dan Butler / Matt Moran \n \nTALENT \nJASPER – Colton Haynes \nMATTHEW – James Scully \nNED – Matthew James Ballinger \nELDER JASPER – James Carey \nMINERS \n-Thomas De Braun \n-Brent Greene \n-Russell Terry \n-Benjamin Wilson \nFARMER – Silas House \nFRIENDS \n-Adam Tanaka \n-Andi Tillman \n-Dara Tiller \n-Casey Campbell\nDOCTOR – Robert Ridhage\nBARTENDER – Ashley Barber \nBAR PATRONS \n-Cameron Bortz\n-Hunter Jones \n-William Arthur\n-Steven Handeland\n-Courtne Moran \n-Kayla Powell\n-Jason Howard\n-Reece Hassell\n \nLABEL – RCA RECORDS\nVP, Video & Visual Content Production - Nicholas Robespierre \nDirector, Video & Visual Content Production - Win Smith \nMarketing – Aaron Stern\nMANAGEMENT \nManager – Ian Thornton\nManager – Michael Corcoran \n\n#TylerChilders #InYourLove #RustinInTheRain",
        },
      },
      contentDetails: {
        duration: "PT4M45S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "776190",
        likeCount: "24966",
        favoriteCount: "0",
        commentCount: "4920",
      },
    },
    {
      kind: "youtube#video",
      etag: "5trObR-VvQ7AZhg1uGX3asm2l_U",
      id: "nbxVfd1bw3s",
      snippet: {
        publishedAt: "2023-07-27T15:00:40Z",
        channelId: "UCPD_bxCRGpmmeQcbe2kpPaA",
        title: "Stephen Curry Is On Fire While Eating Spicy Wings | Hot Ones",
        description:
          "Stephen Curry is the greatest shooter in NBA history and a four-time champion with a pair of MVPs and nine All-Star game appearances to his name. You can see his journey from overlooked prospect to NBA legend in the new documentary, Underrated, which is now available on Apple TV+. But how is he with spicy food? Find out as Steph takes on the wings of death and discusses NBA popcorn power rankings, the shooting mechanics of Klay Thompson, and memorable moments with Kobe Bryant.\n\nBUY HOT ONES HOT SAUCE NOW: https://fwfea.st/hotsauces\n\nTRY THE HOT ONES BONELESS CHICKEN BITE CHALLENGE: https://fwfea.st/chickenbites\n\nBUY HOT ONES TRUTH OR DAB: THE GAME: http://truthordabgame.com\n\nSIGN UP FOR THE HOT ONES MONTHLY HOT SAUCE SUBSCRIPTION: https://bit.ly/2veY50P\n\nSIGN UP FOR THE FIRST WE FEAST NEWSLETTER: http://firstwefeast.com/signup\n\nSUBSCRIBE TO FIRST WE FEAST ON YOUTUBE: http://goo.gl/UxFzhK\n\nMAKE A DIFFERENCE BY DONATING TO COMMON THREADS, THE OFFICIAL  CHARITY PARTNER OF HOT ONES: https://www.commonthreads.org/firstwe...\n\nCheck out more of First We Feast here:\n\nhttp://firstwefeast.com/\nhttp://instagram.com/firstwefeast\nhttp://instagram.com/hotones/\nhttps://twitter.com/firstwefeast\nhttps://www.facebook.com/FirstWeFeast",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/nbxVfd1bw3s/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/nbxVfd1bw3s/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/nbxVfd1bw3s/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/nbxVfd1bw3s/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/nbxVfd1bw3s/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "First We Feast",
        tags: [
          "First we feast",
          "fwf",
          "firstwefeast",
          "food",
          "food porn",
          "cook",
          "cooking",
          "chef",
          "recipe",
          "cocktail",
          "bartender",
          "craft beer",
          "complex",
          "complex networks",
          "spicy food",
          "foodie",
          "burgers",
          "food documentary",
          "steph curry",
          "stephen curry",
          "steph curry highlights",
          "steph curry hot ones",
          "steph curry golf",
          "nba",
          "golden state warriors",
          "warriors",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Stephen Curry Is On Fire While Eating Spicy Wings | Hot Ones",
          description:
            "Stephen Curry is the greatest shooter in NBA history and a four-time champion with a pair of MVPs and nine All-Star game appearances to his name. You can see his journey from overlooked prospect to NBA legend in the new documentary, Underrated, which is now available on Apple TV+. But how is he with spicy food? Find out as Steph takes on the wings of death and discusses NBA popcorn power rankings, the shooting mechanics of Klay Thompson, and memorable moments with Kobe Bryant.\n\nBUY HOT ONES HOT SAUCE NOW: https://fwfea.st/hotsauces\n\nTRY THE HOT ONES BONELESS CHICKEN BITE CHALLENGE: https://fwfea.st/chickenbites\n\nBUY HOT ONES TRUTH OR DAB: THE GAME: http://truthordabgame.com\n\nSIGN UP FOR THE HOT ONES MONTHLY HOT SAUCE SUBSCRIPTION: https://bit.ly/2veY50P\n\nSIGN UP FOR THE FIRST WE FEAST NEWSLETTER: http://firstwefeast.com/signup\n\nSUBSCRIBE TO FIRST WE FEAST ON YOUTUBE: http://goo.gl/UxFzhK\n\nMAKE A DIFFERENCE BY DONATING TO COMMON THREADS, THE OFFICIAL  CHARITY PARTNER OF HOT ONES: https://www.commonthreads.org/firstwe...\n\nCheck out more of First We Feast here:\n\nhttp://firstwefeast.com/\nhttp://instagram.com/firstwefeast\nhttp://instagram.com/hotones/\nhttps://twitter.com/firstwefeast\nhttps://www.facebook.com/FirstWeFeast",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT27M7S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2385727",
        likeCount: "118420",
        favoriteCount: "0",
        commentCount: "6253",
      },
    },
    {
      kind: "youtube#video",
      etag: "1fV70y4hKcVi_8_sM7uP6O1m0W8",
      id: "Fij7x3h_S6Y",
      snippet: {
        publishedAt: "2023-07-27T00:05:04Z",
        channelId: "UCJbYdyufHR-cxOuY96KIoqA",
        title: "AMP FRESHMAN CYPHER 2023",
        description:
          "CHECK OUT APPAREL DROP 2 ⚡ HTTPS://AMP.SHOP\n\nWE RECORDED A PODCAST!! SUB NOW https://www.youtube.com/channel/UC51ypdbMnEyRb9f9MCOg_Vg?sub_confirmation=1\n\nVIDEO DIRECTED & EDITED BY JESSE LOMAX & FOURTH FRAME STUDIOS\n\nAMP AMP AMP AMP\n📸 Follow us on Instagram: https://www.instagram.com/ampexclusive\n🦅 Follow us on Twitter: https://twitter.com/ampexclusive\n\n⚡️⚡️AMP⚡️⚡️\n\n⚡️Fanum aka JustFanum\n🎥 https://www.youtube.com/c/FanumReacts/videos\n📸 https://www.instagram.com/elfanum/\n🦅 https://twitter.com/FanumTV\n\n⚡️Duke aka Duke Dennis\n🎥 https://www.youtube.com/c/DeeBlockDukeDennis\n📸 https://www.instagram.com/duke_dennis/\n🦅 https://twitter.com/ImDukeDennis\n\n⚡️Agent aka Agent 00\n🎥 https://www.youtube.com/user/CallMeAgent00\n📸 https://www.instagram.com/callmeagentzero/\n🦅 https://twitter.com/CallMeAgent00\n\n⚡️Davis aka ImDavisss\n🎥  https://www.youtube.com/c/ItsDavisss\n📸 https://www.instagram.com/imdavisssyt/\n🦅 https://twitter.com/imdavisss\n\n⚡️ Kai aka Kai Cenat\n🎥 https://www.youtube.com/c/KaiCenat\n📸 https://www.instagram.com/kai_cenattv/\n🦅 https://twitter.com/KaiCenat\n\n⚡️Chris aka chrisnxtdoor\n🎥 https://www.youtube.com/watch?v=yEREEVk06ZM\n📸 https://www.instagram.com/chrisnxtdoor_/\n🦅 https://twitter.com/chrisnxtdoor_",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Fij7x3h_S6Y/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "AMP",
        tags: [
          "AMP FRESHMAN CYPHER 2023",
          "AMP CYPHER",
          "AMP FRESHMAN CYPHER",
          "KAI CENAT",
          "DUKE DENNIS",
          "FANUM",
          "AGENT 00",
          "CHRISNXTDOOR",
          "IMDAVISSS",
          "LIL YACHTY",
          "KAYSAN",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "AMP FRESHMAN CYPHER 2023",
          description:
            "CHECK OUT APPAREL DROP 2 ⚡ HTTPS://AMP.SHOP\n\nWE RECORDED A PODCAST!! SUB NOW https://www.youtube.com/channel/UC51ypdbMnEyRb9f9MCOg_Vg?sub_confirmation=1\n\nVIDEO DIRECTED & EDITED BY JESSE LOMAX & FOURTH FRAME STUDIOS\n\nAMP AMP AMP AMP\n📸 Follow us on Instagram: https://www.instagram.com/ampexclusive\n🦅 Follow us on Twitter: https://twitter.com/ampexclusive\n\n⚡️⚡️AMP⚡️⚡️\n\n⚡️Fanum aka JustFanum\n🎥 https://www.youtube.com/c/FanumReacts/videos\n📸 https://www.instagram.com/elfanum/\n🦅 https://twitter.com/FanumTV\n\n⚡️Duke aka Duke Dennis\n🎥 https://www.youtube.com/c/DeeBlockDukeDennis\n📸 https://www.instagram.com/duke_dennis/\n🦅 https://twitter.com/ImDukeDennis\n\n⚡️Agent aka Agent 00\n🎥 https://www.youtube.com/user/CallMeAgent00\n📸 https://www.instagram.com/callmeagentzero/\n🦅 https://twitter.com/CallMeAgent00\n\n⚡️Davis aka ImDavisss\n🎥  https://www.youtube.com/c/ItsDavisss\n📸 https://www.instagram.com/imdavisssyt/\n🦅 https://twitter.com/imdavisss\n\n⚡️ Kai aka Kai Cenat\n🎥 https://www.youtube.com/c/KaiCenat\n📸 https://www.instagram.com/kai_cenattv/\n🦅 https://twitter.com/KaiCenat\n\n⚡️Chris aka chrisnxtdoor\n🎥 https://www.youtube.com/watch?v=yEREEVk06ZM\n📸 https://www.instagram.com/chrisnxtdoor_/\n🦅 https://twitter.com/chrisnxtdoor_",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT14M",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2460476",
        likeCount: "234566",
        favoriteCount: "0",
        commentCount: "29171",
      },
    },
    {
      kind: "youtube#video",
      etag: "2nIQ5qFf9cJILcI6fTDLmeYfWtw",
      id: "fBTNj06FFPc",
      snippet: {
        publishedAt: "2023-07-27T13:00:37Z",
        channelId: "UCR6JgrsJ3RZKO8_eD7LNq_A",
        title: "Lil Yachty: “I’m carrying your conversation on your podcast”",
        description:
          "Inside one of his homes, Bobbi talks to Lil Yachty, who is the same age as her. Over a plate of warm cookies, they uncover the mysteries of life: How old are their kids? How did Lil Yachty choose his name? How do you pronounce Lil? Who is Bobbi, really? This deep conversation however is rudely interrupted by one of Yachty and Bobbi’s mutual best friends.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/fBTNj06FFPc/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/fBTNj06FFPc/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/fBTNj06FFPc/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/fBTNj06FFPc/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/fBTNj06FFPc/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Bobbi Althoff",
        tags: [
          "Bobby Althoff",
          "little Yatchy",
          "bobbi althoff",
          "the really really good podcast",
          "the very good podcast",
          "yatchy",
          "bobby",
          "the good podcast",
          "drake",
          "Bobbi interviews Lil Yachty",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Lil Yachty: “I’m carrying your conversation on your podcast”",
          description:
            "Inside one of his homes, Bobbi talks to Lil Yachty, who is the same age as her. Over a plate of warm cookies, they uncover the mysteries of life: How old are their kids? How did Lil Yachty choose his name? How do you pronounce Lil? Who is Bobbi, really? This deep conversation however is rudely interrupted by one of Yachty and Bobbi’s mutual best friends.",
        },
      },
      contentDetails: {
        duration: "PT1H5M44S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1583508",
        likeCount: "68791",
        favoriteCount: "0",
        commentCount: "6489",
      },
    },
    {
      kind: "youtube#video",
      etag: "wGzFOLsypSDyf4IWXVY6KBEe9fo",
      id: "DLk7nkxgsq8",
      snippet: {
        publishedAt: "2023-07-27T17:21:40Z",
        channelId: "UC7_YxT-KID8kRbqZo7MyscQ",
        title: "Five Nights at Freddy's Security Breach: RUIN - Part 2",
        description:
          "Seems like the daycare isn't quite what it used to be in the Mega Pizzaplex! \nLISTEN TO DISTRACTIBLE ►► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\n\nPlay FNAF Security Breach RUIN ► https://store.steampowered.com/app/1924720/Five_Nights_at_Freddys_Security_Breach__Ruin/\n\nScary Games Playlist ► https://www.youtube.com/playlist?list=PL3tRBEVW0hiBSFOFhTC5wt75P2BES0rAo\n\nHorror Outro ► https://soundcloud.com/shurkofficial/haunted",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/DLk7nkxgsq8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/DLk7nkxgsq8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/DLk7nkxgsq8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/DLk7nkxgsq8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/DLk7nkxgsq8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Markiplier",
        tags: [
          "five nights at freddys security breach",
          "fnaf",
          "markiplier",
          "markiplier security breach",
          "markiplier five nights at freddy's",
          "five nights at freddy's",
          "gaming",
          "gameplay",
          "playthrough",
          "reactions",
          "screaming",
          "jump scares",
          "freddy",
          "chica",
          "bonnie",
          "golden freddy",
          "ruin",
          "ruin dlc",
          "security breach ruin",
          "part 2",
        ],
        categoryId: "20",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Five Nights at Freddy's Security Breach: RUIN - Part 2",
          description:
            "Seems like the daycare isn't quite what it used to be in the Mega Pizzaplex! \nLISTEN TO DISTRACTIBLE ►► https://open.spotify.com/show/2X40qLyoj1wQ2qE5FVpA7x\n\nPlay FNAF Security Breach RUIN ► https://store.steampowered.com/app/1924720/Five_Nights_at_Freddys_Security_Breach__Ruin/\n\nScary Games Playlist ► https://www.youtube.com/playlist?list=PL3tRBEVW0hiBSFOFhTC5wt75P2BES0rAo\n\nHorror Outro ► https://soundcloud.com/shurkofficial/haunted",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT49M13S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2278131",
        likeCount: "154884",
        favoriteCount: "0",
        commentCount: "7459",
      },
    },
  ],
  nextPageToken: "CAUQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 5,
  },
};
